# Site settings
title: Attendance Project Documentation
description: MSU AI Club presents the Attendance Project!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Attendance Project Documentation
user_description: AI Club at Michigan State University
user_title: MSU AI Club
email: anon@anon.com
github_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'node_modules']
